// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID           int64          `json:"id"`
	GroupID      int64          `json:"group_id"`
	Title        string         `json:"title"`
	Amount       string         `json:"amount"`
	Currency     string         `json:"currency"`
	Notes        sql.NullString `json:"notes"`
	DateIncurred sql.NullTime   `json:"date_incurred"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ExpensePayment struct {
	ID        int64  `json:"id"`
	ExpenseID int64  `json:"expense_id"`
	UserID    int64  `json:"user_id"`
	Amount    string `json:"amount"`
}

type ExpenseSplit struct {
	ID        int64       `json:"id"`
	ExpenseID int64       `json:"expense_id"`
	UserID    int64       `json:"user_id"`
	Share     string      `json:"share"`
	Status    interface{} `json:"status"`
}

type Group struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID                int64          `json:"id"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	EmailID           string         `json:"email_id"`
	Phone             sql.NullString `json:"phone"`
	Username          sql.NullString `json:"username"`
	ProfilePictureUrl sql.NullString `json:"profile_picture_url"`
	PasswordHash      string         `json:"password_hash"`
	PasswordSalt      string         `json:"password_salt"`
	AuthProvider      string         `json:"auth_provider"`
	LastLoginAt       time.Time      `json:"last_login_at"`
	IsActive          bool           `json:"is_active"`
	PreferredCurrency string         `json:"preferred_currency"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type UserGroup struct {
	ID       int64     `json:"id"`
	UserID   int64     `json:"user_id"`
	GroupID  int64     `json:"group_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}
